In [1]:
import numpy as np

v = np.zeros(3)
print(v)

[0. 0. 0.]


In [10]:
v1 = np.array([10,20,30],float)
v2 = np.array([1,2,3],float)
v3 = (v2-v1)/7
print(v3)

for i in range(3):
    round(v3[i],3) 
    
print(v3)

[-1.28571429 -2.57142857 -3.85714286]
[-1.28571429 -2.57142857 -3.85714286]
